name: flutter_text
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  event_bus: ^1.1.0
  drag_list: ^1.0.7
  flutter_slidable: ^0.5.4
  flutter_screenutil: ^0.5.2
  sliding_up_panel: ^0.3.6
  liquid_swipe: ^1.3.0
  shared_preferences: ^0.5.0
  image_picker: 0.6.2
  curved_navigation_bar: ^0.3.2
  url_launcher: ^5.2.1
  local_auth: ^0.6.1
  provider: 3.1.0+1
  flutter_speed_dial: ^1.2.4
  table_calendar: 2.2.2
  simple_animations: 1.3.8
  google_sign_in: ^4.0.12
  firebase_analytics: ^5.0.2
  firebase_auth: ^0.15.0
  firebase_storage: ^3.0.10
  firebase_database: ^3.0.9
  firebase_core: ^0.4.0+9
  http: ^0.12.0+4
  photo_view: ^0.4.2
  agora_rtc_engine: ^1.0.1
  video_player: ^0.10.2+5
  orientation: ^1.1.0
  common_utils: ^1.1.3
  dio: ^3.0.9
  intl: ^0.16.1
  audioplayers: 0.13.6
  image_picker_saver: 0.3.0
  permission_handler: ^3.0.0
  flutter_full_pdf_viewer: ^1.0.6
  flutter_staggered_animations: ^0.1.2
  qrscan: ^0.2.17

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - images/lake.jpg
    - images/111.png
    - images/timg.jpg
    - images/timg2.jpg
    - images/timg3.jpg
    - images/sun.jpg
    - images/plane1.gif
    - images/plane2.gif
    - images/oneday.gif
    - images/cloud3.gif
    - images/cloud2.gif
    - images/cloud1.gif
    - images/cloud5.gif
    - images/weather/
    - images/_cat_sky.jpg
    - assets/index.pdf

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
